version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      create-database-app-dependencies:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "create-database-app"
    commit-message:
      prefix: fix(deps)

  - package-ecosystem: "npm" 
    directory: "/templates/node-angular/"
    schedule:
      interval: "monthly"
    groups:
      angular-dependencies:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "templates-angular"
    commit-message:
      prefix: fix(deps)

  - package-ecosystem: "npm" 
    directory: "/templates/node-jet/"
    schedule:
      interval: "monthly"
    groups:
      jet-dependencies:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "templates-jet"
    commit-message:
      prefix: fix(deps)

  - package-ecosystem: "npm" 
    directory: "/templates/node-react/"
    schedule:
      interval: "monthly"
    groups:
      react-dependencies:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "templates-react"
    commit-message:
      prefix: fix(deps)

  - package-ecosystem: "npm" 
    directory: "/templates/node-react-todo/"
    schedule:
      interval: "monthly"
    groups:
      react-todo-dependencies:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "templates-react-todo"
    commit-message:
      prefix: fix(deps)

  - package-ecosystem: "npm" 
    directory: "/templates/node-vanilla/"
    schedule:
      interval: "monthly"
    groups:
      js-vanilla-dependencies:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "templates-vanilla"
    commit-message:
      prefix: fix(deps)

  - package-ecosystem: "npm" 
    directory: "/templates/node-vue/"
    schedule:
      interval: "monthly"
    groups:
      vue-dependencies:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "templates-vue"
    commit-message:
      prefix: fix(deps)
