version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "create-database-app"
    commit-message:
      prefix: fix(deps)
      prefix-development: chore(dev-deps)

  - package-ecosystem: "npm" 
    directory: "/templates/node-angular/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "templates-angular"
    commit-message:
      prefix: fix(deps)
      prefix-development: chore(dev-deps)

  - package-ecosystem: "npm" 
    directory: "/templates/node-jet/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "templates-jet"
    commit-message:
      prefix: fix(deps)
      prefix-development: chore(dev-deps)

  - package-ecosystem: "npm" 
    directory: "/templates/node-react/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "templates-react"
    commit-message:
      prefix: fix(deps)
      prefix-development: chore(dev-deps)

  - package-ecosystem: "npm" 
    directory: "/templates/node-react-todo/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "templates-react-todo"
    commit-message:
      prefix: fix(deps)
      prefix-development: chore(dev-deps)

  - package-ecosystem: "npm" 
    directory: "/templates/node-vanilla/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "templates-vanilla"
    commit-message:
      prefix: fix(deps)
      prefix-development: chore(dev-deps)

  - package-ecosystem: "npm" 
    directory: "/templates/node-vue/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "templates-vue"
    commit-message:
      prefix: fix(deps)
      prefix-development: chore(dev-deps)
