version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "create-database-app"

  - package-ecosystem: "npm" 
    directory: "/templates/node-angular/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "templates-angular"

  - package-ecosystem: "npm" 
    directory: "/templates/node-jet/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "templates-jet"

  - package-ecosystem: "npm" 
    directory: "/templates/node-react/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "templates-react"

  - package-ecosystem: "npm" 
    directory: "/templates/node-react-todo/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "templates-react-todo"

  - package-ecosystem: "npm" 
    directory: "/templates/node-vanilla/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "templates-vanilla"

  - package-ecosystem: "npm" 
    directory: "/templates/node-vue/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "templates-vue"
