#!/bin/bash

set -euo pipefail

pushd "$(dirname "${BASH_SOURCE[0]}")"

# Load autogenerated secrets from .env.stage.auto
source "../.env.stage.auto"

source ./db_connect.sh

# Ensure required environment variables are set
: "${MLE_APP_USER_NAME:?You must set MLE_APP_USER_NAME}"
: "${MLE_APP_USER_STAGE_PASS:?You must set MLE_APP_USER_STAGE_PASS}"
: "${MLE_APP_WALLET_STAGE_PASS:?You must set MLE_APP_WALLET_STAGE_PASS}"

connect_stage_admin @./user-setup.sql $MLE_APP_USER_NAME $MLE_APP_USER_STAGE_PASS

popd
