#!/bin/bash
# Script to deploy DB migrations and sync ORDS endpoints for staging/ATP Oracle DB

set -euo pipefail

pushd "$(dirname "${BASH_SOURCE[0]}")"

# Load autogenerated secrets from .env.stage.auto
source ../.env.stage.auto
source ./db_connect.sh

# Ensure required environment variables are set
: "${MLE_APP_USER_NAME:?You must set MLE_APP_USER_NAME}"
: "${MLE_APP_USER_STAGE_PASS:?You must set MLE_APP_USER_STAGE_PASS}"
: "${MLE_APP_WALLET_STAGE_PASS:?You must set MLE_APP_WALLET_STAGE_PASS}"

echo $MLE_APP_USER_NAME
echo $MLE_APP_USER_STAGE_PASS
echo $MLE_APP_WALLET_STAGE_PASS

echo "Starting Liquibase migrations for staging DB user $MLE_APP_USER_NAME..."
connect_stage_app << EOF
  lb update -changelog-file=migrations.json
EOF
echo "Migrations completed."

echo "Synchronizing ORDS endpoints from src/routes with mle-cliw (staging config)..."
MLECLI_USERNAME="$MLE_APP_USER_NAME" MLECLI_WALLET_PASS="$MLE_APP_WALLET_STAGE_PASS" MLECLI_PASSWORD="$MLE_APP_USER_STAGE_PASS" mle-cli --experimental build --config ../mleclistage.json create ords-fs
echo "ORDS API configuration completed."

popd
